### ISSUE TITLE
Does not work for ansible 2.x

### ISSUE THREAD

**Issue by memelet** [retr0h/ansible-logrotate#22]
The only change I had to make was to explicitly define the type for 'options':
```
            options    = dict(type='list',
                              default=['daily',
                                       'missingok',
                                        ...
```

**Comment by retr0h** [comment]
Hi @memelet.  I believe you are using an old version.  Please pull master, and let me know if that works.

**Comment by memelet** [comment]
Yes, you are correct. I was using an old version. I really wish there some better way to manage dependencies than manually deleting and the re-running requirements.txt.

Sorry for the noise.

**Comment by retr0h** [comment]
all good
