### ISSUE TITLE
Old version on galaxy

### ISSUE THREAD

**Issue by tjoelsson** [retr0h/ansible-logrotate#25]
Recently when downloading this role from galaxy I'm getting an older version. Looks like there might be a problem with the tags. 1.0 and 2.0 are pointing to the same commit. Is this correct?

Using the logrotate module with the version from galaxy creates configuration files with one letter on each line:

```
# Generated by Ansible.
# Local modifications will be overwritten.

/var/log/*.log {
  [
  '
  d
  a
  i
  l
  y
  '
  ,
   
  '
  m
  i
  s
  s
  i
  n
  g
  o
  k
  '
  ,
   
  '
  r
  o
  t
  a
  t
  e
   
  8
  '
  ,
   
  '
  c
  o
  m
  p
  r
  e
  s
  s
  '
  ,
   
  '
  d
  e
  l
  a
  y
  c
  o
  m
  p
  r
  e
  s
  s
  '
  ,
   
  '
  c
  o
  p
  y
  t
  r
  u
  n
  c
  a
  t
  e
  '
  ,
   
  '
  n
  o
  t
  i
  f
  e
  m
  p
  t
  y
  '
  ]
}
```

**Comment by retr0h** [comment]
See the usage in the molecule test playbook.  Usage changed between v1 and v2.

**Comment by tjoelsson** [comment]
I'm using it the same way as that playbook. The problem is I'm getting the wrong version off of galaxy. For now, I'm downloading the role directly from github to make it work.

**Comment by retr0h** [comment]
Ah, got ya.  Yeah, I pretty much don't use galaxy.  I even wrote a [replacement](github.com/metacloud/gilt).

**Comment by tjoelsson** [comment]
We rely on using this role through galaxy in several projects. Any chance you can fix the version tags so the latest version is imported correctly, or do I need to fork it and import my own?

**Comment by retr0h** [comment]
65c8a4e35f7e59ff250c5cd5526ff752a2905cac looks to be the v1.0 tag SHA you desire.  Can you confirm?

**Comment by retr0h** [comment]
I've cut a 2.0.1 tag which pointed at the current HEAD.

**Comment by tjoelsson** [comment]
I see the new version on Galaxy now. Thank you.
